env:
  es2020: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - 'testing-library'
  - jest
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
rules:
  testing-library/await-async-query: error
  testing-library/no-await-sync-query: error
  testing-library/no-debugging-utils: off
  testing-library/no-dom-import: off